# scripts/check_regression.ps1
# Auto-generated by Phase 3 — BENCH-03 regression gate.
# Usage: pwsh scripts/check_regression.ps1
# Prerequisites: Maven 3.9.15 at C:\Users\Admin\.maven\maven-3.9.15\bin

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$BaselinePath = '.planning/phases/03-numerical-accuracy-hardening/03-baseline.json'
$CsvDir = 'target'
$InternalRuns = 3
$PerfRegressionPct = 15.0

$env:Path = 'C:\Users\Admin\.maven\maven-3.9.15\bin;' + $env:Path

Write-Host '[1/3] Building JMH jar...' -ForegroundColor Cyan
& mvn -pl bench -am package -DskipTests | Out-Null
if ($LASTEXITCODE -ne 0) { Write-Error 'mvn package failed'; exit 1 }

Write-Host "[2/3] Running JMH benchmarks ($InternalRuns runs, taking median)..." -ForegroundColor Cyan
# Hybrid P/E variance (Phase 2 CI was ±93% on sum_reduce) makes single-run comparison unreliable.
# Aggregate $InternalRuns runs per benchmark; median of N=3 narrows the swing.
$allRuns = @()
for ($i = 1; $i -le $InternalRuns; $i++) {
    $csv = "$CsvDir/jmh-phase3-run-$i.csv"
    Write-Host "  Run $i/$InternalRuns..."
    & java -jar bench/target/benchmarks.jar -f 1 -wi 3 -i 3 -w 1s -r 1s -rf csv -rff $csv | Out-Null
    if ($LASTEXITCODE -ne 0) { Write-Error "JMH run $i failed"; exit 1 }
    if (-not (Test-Path $csv)) { Write-Error "CSV output not found at $csv"; exit 1 }
    $rows = Import-Csv $csv
    foreach ($r in $rows) {
        $allRuns += [PSCustomObject]@{
            Benchmark = $r.benchmark -replace '^bench\.CoreBench\.', ''
            N = ($r.'Param: n' -as [string]).Trim()
            Score = [double]$r.Score
        }
    }
    Remove-Item $csv -Force -ErrorAction SilentlyContinue
}

# Aggregate by (Benchmark, N): take median score.
$aggregated = $allRuns | Group-Object Benchmark, N | ForEach-Object {
    $sorted = $_.Group.Score | Sort-Object
    $count = $sorted.Count
    $median = if ($count % 2 -eq 1) { $sorted[[Math]::Floor($count/2)] } else { ($sorted[$count/2 - 1] + $sorted[$count/2]) / 2.0 }
    [PSCustomObject]@{ Benchmark = $_.Group[0].Benchmark; N = $_.Group[0].N; Score = $median }
}

Write-Host '[3/3] Diffing against baseline (median over runs)...' -ForegroundColor Cyan
$baseline = Get-Content $BaselinePath -Raw | ConvertFrom-Json

$gateFailed = $false
foreach ($entry in $baseline.perf_benchmarks) {
    $bench = $entry.benchmark
    $n = $entry.params.n
    $baselineScore = [double]$entry.score_ms
    $tol = [double]$entry.tolerance_pct
    $key = "$bench.$n"

    $match = $aggregated | Where-Object {
        $_.Benchmark -eq $bench -and (($_.N -eq '' -and $n -eq 10000000) -or ($_.N -eq ([string]$n)))
    } | Select-Object -First 1
    if (-not $match) {
        Write-Host "[PERF] SKIP  $key (no matching JMH row)" -ForegroundColor Yellow
        continue
    }

    $measured = [double]$match.Score
    $deltaPct = (($measured - $baselineScore) / $baselineScore) * 100.0
    $status = if ([Math]::Abs($deltaPct) -gt $tol) {
        $gateFailed = $true
        'REGRESSION'
    } else { 'PASS' }
    $color = if ($status -eq 'REGRESSION') { 'Red' } else { 'Green' }
    Write-Host ("[PERF] {0} {1} measured={2:N3}ms baseline={3:N3}ms ({4}{5:N2}%)" -f $status, $key, $measured, $baselineScore, $(if ($deltaPct -ge 0) { '+' } else { '' }), $deltaPct) -ForegroundColor $color
}

Write-Host ''
Write-Host 'Accuracy checks (enforced by mvn test -Dtest=AccuracyHardeningTest, NOT by this script):' -ForegroundColor Cyan
foreach ($acc in $baseline.accuracy_checks) {
    Write-Host ("[ACCURACY] {0} max_rel_err={1} fixture={2} enforced_by={3}" -f $acc.op, $acc.max_rel_err, $acc.fixture, $acc.enforced_by)
}

if ($gateFailed) {
    Write-Error 'Regression gate FAILED'
    exit 1
}
Write-Host '[3/3] PASS: all perf checks within tolerance.' -ForegroundColor Green
